services:
  - type: web
    name: vialifecoach-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    sourceDir: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://www.vialifecoach.org,https://vialifecoach.org
      - key: FRONTEND_URL
        value: https://vialifecoach.org
      - key: EMAIL_HOST
        value: smtp.zoho.com
      - key: EMAIL_PORT
        value: "465"
      - key: EMAIL_USE_TLS
        value: "false"
      - key: EMAIL_USE_SSL
        value: "true"
      - key: EMAIL_HOST_USER
        value: support@vialifecoach.org
      - key: DEFAULT_FROM_EMAIL
        value: Vialifecoach <support@vialifecoach.org>
